// <auto-generated />
using System;
using CarBookingApp.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBookingApp.Data.Migrations
{
    [DbContext(typeof(CarBookAppDbContext))]
    [Migration("20240131034217_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarBookingApp.Data.Models.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = new Guid("19723339-1eae-4cad-bc45-8736234d8768"),
                            Name = "Toyota Corolla",
                            Year = 2020
                        },
                        new
                        {
                            CarId = new Guid("2a06d250-fba0-4606-8b3b-bce0dddc2ccc"),
                            Name = "Honda Civic",
                            Year = 2018
                        },
                        new
                        {
                            CarId = new Guid("7242fc72-dd55-462e-b16b-c4915b81629d"),
                            Name = "Nissan Sentra",
                            Year = 2017
                        },
                        new
                        {
                            CarId = new Guid("829ba0e3-19d2-482f-ba88-37f00d9dab5e"),
                            Name = "Ford Focus",
                            Year = 2016
                        },
                        new
                        {
                            CarId = new Guid("fe8d2ab1-db2e-40e8-a049-1f50a9f1f347"),
                            Name = "Chevrolet Cruze",
                            Year = 2015
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
