// <auto-generated />
using System;
using CarBookingApp.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBookingApp.Data.Migrations
{
    [DbContext(typeof(CarBookAppDbContext))]
    partial class CarBookAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarBookingApp.Data.Models.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = new Guid("68a2010e-7f25-44af-8e4e-fa2458b17857"),
                            Name = "Toyota Corolla",
                            Year = 2019
                        },
                        new
                        {
                            CarId = new Guid("d1d14888-ca7c-4c65-8a44-30fa550d1f3c"),
                            Name = "Honda Civic",
                            Year = 2018
                        },
                        new
                        {
                            CarId = new Guid("998c183d-baaa-48a3-8fe7-73bde3297358"),
                            Name = "Nissan Sentra",
                            Year = 2017
                        },
                        new
                        {
                            CarId = new Guid("d120c20a-6a9d-49e3-982e-4c2178340add"),
                            Name = "Ford Focus",
                            Year = 2016
                        },
                        new
                        {
                            CarId = new Guid("c959f47d-ccc4-488d-950c-724c985b2ba5"),
                            Name = "Chevrolet Cruze",
                            Year = 2015
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
